# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/eyre921/default-dev-env:latest
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: start 1P
          script: 1pctl start all
        - name: install env
          script: pnpm install && pnpm build 

# .cnb.yml

master:
  push:
    - imports:
        - https://cnb.cool/eyre921/secret/-/blob/main/edgeone-pages-env.yml
      runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/eyre921/default-dev-env:latest
      
      stages:
        - name: Build Site
          script:
            - pnpm i
            - pnpm build

        - name: Deploy to EdgeOne Pages
          script:
            - npm install -g edgeone 
            - npx edgeone pages deploy ./docs/.vitepress/dist -n vibe-vibe-production --force -t $EDGEONE_API_TOKEN

develop:
  push:
    - imports:
        - https://cnb.cool/eyre921/secret/-/blob/main/edgeone-pages-env.yml
      runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/eyre921/default-dev-env:latest
      
      stages:
        - name: Build Site
          script:
            - pnpm i
            - pnpm build

        - name: Deploy to EdgeOne Pages
          script:
            - npm install -g edgeone 
            - npx edgeone pages deploy ./docs/.vitepress/dist -n vibe-vibe-develop --force -t $EDGEONE_API_TOKEN